### ISSUE TITLE
Issue to update in virtualenv on Python 3.7

### ISSUE THREAD

**Issue by SteveClement** [viper-framework/ScrapySplashWrapper#2]
Not sure what is going on, it does install but fails at the same time.

```bash
./venv/bin/pip install -U git+https://github.com/viper-framework/ScrapySplashWrapper.git#egg=Scrapy 


Collecting Scrapy from git+https://github.com/viper-framework/ScrapySplashWrapper.git#egg=Scrapy
  Cloning https://github.com/viper-framework/ScrapySplashWrapper.git to /tmp/pip-install-qlmkr2j6/Scrapy
  Running setup.py (path:/tmp/pip-install-qlmkr2j6/Scrapy/setup.py) egg_info for package Scrapy produced metadata for project name scrapysplashwrapper. Fix your #egg=Scrapy fragments.
Requirement already satisfied, skipping upgrade: scrapy-splash in ./venv/lib/python3.7/site-packages (from scrapysplashwrapper) (0.7.2)
Building wheels for collected packages: scrapysplashwrapper, scrapysplashwrapper
  Running setup.py bdist_wheel for scrapysplashwrapper ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mhyskmf/wheels/16/3f/bb/3bb672dc8adb372cd26168a2eef53a75b1c55058d3f5c81bf5
  Running setup.py bdist_wheel for scrapysplashwrapper ... error
  Complete output from command /usr/local/src/viper/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qlmkr2j6/scrapysplashwrapper/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-r3juxjnk --python-tag cp37:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/src/viper/venv/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qlmkr2j6/scrapysplashwrapper/setup.py'
  
  ----------------------------------------
  Failed building wheel for scrapysplashwrapper
  Running setup.py clean for scrapysplashwrapper
  Complete output from command /usr/local/src/viper/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qlmkr2j6/scrapysplashwrapper/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/src/viper/venv/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qlmkr2j6/scrapysplashwrapper/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for scrapysplashwrapper
Successfully built scrapysplashwrapper
Failed to build scrapysplashwrapper
Installing collected packages: scrapysplashwrapper
  Found existing installation: ScrapySplashWrapper 0.1
    Uninstalling ScrapySplashWrapper-0.1:
      Successfully uninstalled ScrapySplashWrapper-0.1
Successfully installed scrapysplashwrapper-0.1
```

**Comment by SteveClement** [comment]
Indeed, that just worked.

**Comment by SteveClement** [comment]
But in the requirements-modules.txt the other one is present, fyi.

**Comment by Rafiot** [comment]
yeah, I need to move all that to pipenv.
